name: Java CI with Gradle in smRt store

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main","develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    ## create application.yml
    - name: make application.yml
      run:
        touch ./src/main/resources/application.yml
      shell: bash
    - name: deliver application.yml
      run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
      shell: bash

      ## Gradle Wrapper 권한 부여
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

      ## Gradle Test를 실행한다
    - name: Test with Gradle
      run: ./gradlew --info test

      ## Test 후 Report 생성
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/build/test-results/test/TEST-*.xml'

    ## 오류가 나는 부분에 코멘트를 달아줌
    - name: add comments to a pull request
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

